language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
 - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - echo "apc.enable_cli=on" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
